print("C:\windows")
print("안녕하세요.\n만나서\t\t반갑습니다.")
print("오늘은", "일요일")
print("naver", "kakao", "sk", "samsun", sep=";")
print("naver", "kakao", "sk", "samsun", sep="/")
print("first", end='');print("second")
print(5/3)
